#!/usr/bin/env perl

# This script rebuilds the 'content' directory for every entry.
# Useful if you change what's stored in those directories while
# a comp is underway.

use warnings;
use strict;
use FindBin;
use Path::Class;

use lib "$FindBin::Bin/../lib";
use IFComp::Schema;

my $schema = IFComp::Schema->connect( 'dbi:mysql:ifcomp', 'root', '' );
$schema->entry_directory( Path::Class::Dir->new( "$FindBin::Bin/../entries" ) );

my $current_comp = $schema->resultset( 'Comp' )->current_comp;

for my $entry ( $current_comp->entries ) {
    next unless $entry->main_file;
    print "Updating " . $entry->title . " by " . $entry->author->name . " (" . $entry->platform .")...\n";
    $entry->update_content_directory;
}
