#!/usr/bin/env perl

# This script rebuilds the 'content' directory for every entry.
# Useful if you change what's stored in those directories while
# a comp is underway.
#
# Call with arguments to rebuild only those entries.

use warnings;
use strict;
use FindBin;
use Path::Class;
use Try::Tiny;
use Cwd qw(abs_path);

use lib "$FindBin::Bin/../lib";
use IFComp::Schema;

my $path = abs_path("$FindBin::Bin/../entries");
print "Path = $path\n";
my $schema = IFComp::Schema->connect( 'dbi:mysql:ifcomp', 'root', '' );
$schema->entry_directory( Path::Class::Dir->new($path) );

my @entries = map { $schema->resultset( 'Entry' )->find($_) } @ARGV;

unless (@entries) {
    my $current_comp = $schema->resultset( 'Comp' )->current_comp;
    @entries = $current_comp->entries;
}

for my $entry ( @entries ) {
    next unless $entry->main_file;
    print "Updating " . $entry->title . " by " . $entry->author->name . " (" . $entry->platform .")...\n";
    try {
        $entry->update_content_directory;
    }
    catch {
        print "GOT ERROR: $_\n";
    };
}
