requires 'Catalyst::Runtime' => '5.90053';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Moose';
requires 'namespace::autoclean';
requires 'Config::General';

requires 'Catalyst::Test';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Authentication::Store::DBIx::Class', '>= 0.1506';
requires 'Catalyst::View::TT';
requires 'Catalyst::Plugin::PageCache';
requires 'Catalyst::Plugin::Cache';
requires 'Cache::FastMmap';
requires 'DateTime';
requires 'JSON::Any';
requires 'MooseX::MarkAsMethods';
requires 'MooseX::NonMoose';
requires 'Lingua::EN::Numbers::Ordinate';
requires 'SQL::Translator';

requires 'MooseX::ClassAttribute';
requires 'Email::Sender::Simple';
requires 'Email::MIME::Kit';
requires 'Data::GUID';
requires 'HTML::FormHandler::Moose';
requires 'DateTime::Format::SQLite';
requires 'Email::MIME::Kit::Renderer::TT';


test_requires 'Test::More' => '0.88';
test_requires 'Test::WWW::Mechanize::Catalyst';
