package IFComp::Model::IFCompDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'IFComp::Schema',
);


sub ACCEPT_CONTEXT {
    my $self = shift;
    my ( $c ) = @_;

    $self->schema->email_template_basedir( $c->path_to( 'mail' ) );

    unless ( $self->schema->entry_directory ) {
        $self->schema->entry_directory( $c->path_to( 'entries' ) );
    }

    return $self;

}

=head1 NAME

IFComp::Model::IFCompDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<IFComp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<IFComp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.62

=head1 AUTHOR

Jason McIntosh

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
