package IFComp::Model::IFCompDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'IFComp::Schema',

    # TODO: Remove these values/get them from a local conf
    connect_info => {
        dsn => 'dbi:mysql:dbname=ifcomp',
        user => 'root',
        password => '',
    }
);

=head1 NAME

IFComp::Model::IFCompDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<IFComp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<IFComp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.62

=head1 AUTHOR

Jason McIntosh

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
